AllCops:
  TargetRubyVersion: 3.0

Naming/PredicateName:
  Exclude: ["lib/services/property_matcher.rb"]

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
